Repository WildCodeSchool/202302-orleans-php-project-makesense, pull requests merged in 2023-06, with the labels that each got.

#2 initialisation
  assets/app.js
  assets/styles/_wcs.scss
  assets/styles/app.scss
  assets/styles/variables.scss
  package.json
  templates/base.html.twig
  yarn.lock
Labels: REVIEWED

#3 S01US5
  assets/styles/app.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/fos_ckeditor.yaml
  config/packages/translation.yaml
  config/packages/twig.yaml
  migrations/Version20230606135924.php
  migrations/Version20230607134839.php
  package.json
  src/Controller/DecisionController.php
  src/Entity/Decision.php
  src/Form/DecisionType.php
  src/Repository/DecisionRepository.php
  symfony.lock
  templates/decision/_delete_form.html.twig
  templates/decision/_form.html.twig
  templates/decision/edit.html.twig
  templates/decision/index.html.twig
  templates/decision/new.html.twig
  templates/decision/show.html.twig
  webpack.config.js
  yarn.lock
Labels: REVIEWED, Read please

#5 navbar
  assets/images/LOGO_WILD_CODE_SCHOOL.png
  assets/images/bell.svg
  assets/images/menu.svg
  assets/images/profile.svg
  assets/styles/_navbar.scss
  assets/styles/app.scss
  composer.lock
  templates/base.html.twig
  templates/components/_navbar.html.twig
Labels: REVIEWED, Conflict resolve

#7 S01 us07
  .env
  assets/images/environement.jpg
  assets/images/profil.png
  assets/styles/_decisionCards.scss
  assets/styles/app.scss
  assets/styles/variables.scss
  composer.json
  composer.lock
  migrations/Version20230608100210.php
  src/Controller/HomeController.php
  src/DataFixtures/DecisionFixtures.php
  templates/components/_decisionCards.html.twig
  templates/home/index.html.twig
Labels: REVIEWED, Conflict resolve

#9 fix-style
  assets/styles/app.scss
  templates/decision/new.html.twig
Labels: REVIEWED

#15 fix migration
  migrations/Version20230609090257.php
  migrations/Version20230609092639.php
  migrations/Version20230614093334.php
Labels: REVIEWED

#14 login
  assets/images/fond-login.png
  assets/images/key.svg
  assets/images/mail.svg
  assets/styles/app.scss
  assets/styles/login.scss
  assets/styles/variables.scss
  composer.json
  composer.lock
  config/packages/security.yaml
  config/routes.yaml
  migrations/Version20230609183006.php
  migrations/Version20230614093334.php
  src/Controller/LoginController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  templates/base.html.twig
  templates/components/_navbar.html.twig
  templates/login/index.html.twig
  webpack.config.js
Labels: REVIEWED

#17 S01 us37 status
  assets/styles/_decisionCards.scss
  migrations/Version20230609100751.php
  migrations/Version20230609183006.php
  migrations/Version20230614093334.php
  migrations/Version20230614130259.php
  src/Controller/HomeController.php
  src/Controller/StatusController.php
  src/DataFixtures/DecisionFixtures.php
  src/DataFixtures/StatusFixtures.php
  templates/components/_decisionCards.html.twig
  templates/components/_decisionNavbar.html.twig
  templates/status/index.html.twig
Labels: REVIEWED

#18 start home page
  assets/images/logo-dark.png
  assets/images/map.png
  assets/styles/app.scss
  assets/styles/home.scss
  src/Controller/HomeController.php
  templates/base.html.twig
  templates/components/_decisionCards.html.twig
  templates/home/index.html.twig
Labels: REVIEWED

#21 S02 us40 home page 2
  assets/styles/_decisionCards.scss
  assets/styles/home.scss
  src/Controller/HomeController.php
  templates/home/index.html.twig
Labels: REVIEWED

#22 admin tableau user
  assets/styles/admin.scss
  composer.json
  composer.lock
  src/Controller/AdminUserController.php
  src/Form/UserType.php
  templates/adminLayout.html.twig
  templates/admin_user/_delete_form.html.twig
  templates/admin_user/_form.html.twig
  templates/admin_user/edit.html.twig
  templates/admin_user/index.html.twig
  templates/admin_user/new.html.twig
  templates/icons/pencil.svg
  webpack.config.js
Labels: REVIEWED

#24 fix route
  templates/components/_navbar.html.twig
Labels: REVIEWED

#26 fixed style
  assets/styles/_decisionCards.scss
  src/DataFixtures/DecisionFixtures.php
  templates/components/_decisionCards.html.twig
  templates/components/_decisionNavbar.html.twig
Labels: REVIEWED

#28 a little bit style for the presentation tomorrow
  assets/styles/_buttonTop.scss
  assets/styles/_decisionCards.scss
  assets/styles/home.scss
  assets/styles/variables.scss
  templates/components/_decisionCards.html.twig
  templates/components/_decisionNavbar.html.twig
  templates/components/_footer.html.twig
  templates/decision/new.html.twig
  templates/home/index.html.twig
Labels: REVIEWED, Conflict resolve

#29 S02US11
  migrations/Version20230614135234.php
  src/Controller/DecisionController.php
  src/DataFixtures/CommentFixtures.php
  src/DataFixtures/DecisionFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Comment.php
  src/Entity/Decision.php
  src/Entity/User.php
  src/Form/CommentType.php
  src/Repository/CommentRepository.php
  templates/decision/show.html.twig
Labels: REVIEWED, Conflict resolve

#32 admin navbar/home
  assets/images/mapCreme.png
  assets/styles/adminLayout.scss
  assets/styles/admin_user.scss
  src/Controller/AdminController.php
  templates/admin/adminLayout.html.twig
  templates/admin/admin_user/_delete_form.html.twig
  templates/admin/admin_user/_form.html.twig
  templates/admin/admin_user/edit.html.twig
  templates/admin/admin_user/index.html.twig
  templates/admin/admin_user/new.html.twig
  templates/admin/index.html.twig
  templates/admin_user/_delete_form.html.twig
  templates/admin_user/edit.html.twig
  templates/admin_user/new.html.twig
  templates/components/_navbar_admin.html.twig
  webpack.config.js
Labels: REVIEWED

#31 fix style form
  assets/styles/_decisionCards.scss
  assets/styles/variables.scss
  templates/components/_decisionCards.html.twig
  templates/decision/_delete_form.html.twig
  templates/decision/_form.html.twig
  templates/decision/edit.html.twig
  templates/decision/new.html.twig
Labels: REVIEWED

#34 table category ok
  assets/styles/admin_user.scss
  migrations/Version20230621085807.php
  src/Controller/AdminCategoryController.php
  src/DataFixtures/CategoryFixtures.php
  src/Entity/Category.php
  src/Entity/Decision.php
  src/Form/CategoryType.php
  src/Repository/CategoryRepository.php
  templates/admin_category/_delete_form.html.twig
  templates/admin_category/_form.html.twig
  templates/admin_category/edit.html.twig
  templates/admin_category/index.html.twig
  templates/admin_category/new.html.twig
  templates/admin_category/show.html.twig
Labels: REVIEWED, Conflict resolve

#35 fix admin_user
  assets/styles/admin_user.scss
  assets/styles/variables.scss
  src/Controller/AdminController.php
  src/Repository/UserRepository.php
  templates/admin/admin_user/index.html.twig
Labels: REVIEWED, Conflict resolve

#33 ajout-decision modif
  assets/styles/addDecision.scss
  migrations/Version20230619151517.php
  src/Controller/DecisionController.php
  src/Entity/Decision.php
  src/Entity/User.php
  src/Form/DecisionType.php
  templates/components/_navbar.html.twig
  templates/decision/_form.html.twig
  templates/decision/new.html.twig
  templates/decision/show.html.twig
  webpack.config.js
Labels: REVIEWED, Conflict resolve

#30 S03 us44 search bar
  assets/images/search.svg
  assets/styles/_decisionCards.scss
  assets/styles/variables.scss
  src/Controller/StatusController.php
  src/Form/SearchDecisionType.php
  src/Repository/DecisionRepository.php
  src/Repository/StatusRepository.php
  templates/components/_decisionCards.html.twig
  templates/components/_decisionNavbar.html.twig
  templates/components/_search_form.html.twig
  templates/home/index.html.twig
  templates/status/index.html.twig
Labels: REVIEWED, Conflict resolve

#37 fix migration
  migrations/Version20230619151517.php
  src/Entity/Decision.php
Labels: REVIEWED

#38 fix table user migration and navbar
  migrations/Version20230622085608.php
  src/Entity/Decision.php
  src/Entity/User.php
  templates/components/_navbar.html.twig
Labels: REVIEWED

#36 category new ok
  src/Controller/AdminCategoryController.php
  src/Controller/DecisionSearchController.php
  src/DataFixtures/DecisionFixtures.php
  templates/admin/admin_category/_delete_form.html.twig
  templates/admin/admin_category/_form.html.twig
  templates/admin/admin_category/edit.html.twig
  templates/admin/admin_category/index.html.twig
  templates/admin/admin_category/new.html.twig
  templates/admin/admin_category/show.html.twig
  templates/components/_decisionCards.html.twig
  templates/home/index.html.twig
Labels: REVIEWED, Conflict resolve

#41 category delete ok
  src/Controller/AdminCategoryController.php
  src/Form/CategoryType.php
  templates/admin/admin_category/_delete_form.html.twig
  templates/admin/admin_category/_form.html.twig
  templates/admin/admin_category/edit.html.twig
  templates/admin/admin_category/index.html.twig
  templates/admin/admin_category/new.html.twig
  templates/icons/cross.svg
Labels: REVIEWED, Conflict resolve

#43 style ok
  assets/images/bell.svg
  assets/images/card.png
  assets/images/menu.svg
  assets/images/profile.svg
  assets/styles/_decisionCards.scss
  assets/styles/_navbar.scss
  assets/styles/home.scss
  templates/base.html.twig
  templates/components/_decisionCards.html.twig
  templates/components/_navbar.html.twig
  templates/components/_navbar_admin.html.twig
  templates/home/index.html.twig
Labels: REVIEWED, Conflict resolve

#47 relate category
  assets/styles/addDecision.scss
  src/Form/DecisionType.php
  src/Form/SearchDecisionType.php
  templates/components/_decisionCards.html.twig
  templates/components/_navbar_admin.html.twig
  templates/components/_search_form.html.twig
  templates/decision/show.html.twig
  templates/home/index.html.twig
Labels: REVIEWED

#48 table and fixtures user_situation ok
  migrations/Version20230623140817.php
  migrations/Version20230623141135.php
  src/DataFixtures/CommentFixtures.php
  src/DataFixtures/DecisionFixtures.php
  src/DataFixtures/UserFixtures.php
  src/DataFixtures/UserSituationFixtures.php
  src/Entity/User.php
  src/Entity/UserSituation.php
  src/Repository/UserSituationRepository.php
Labels: REVIEWED
