Repository WildCodeSchool/202302-orleans-php-project-makesense, pull requests merged in 2023-07, with the labels that each got.

#50 impacted and expert user ok
  assets/controllers.json
  assets/styles/addDecision.scss
  assets/styles/login.scss
  composer.json
  composer.lock
  config/bundles.php
  config/routes/ux_autocomplete.yaml
  migrations/Version20230703120134.php
  package.json
  src/DataFixtures/DecisionFixtures.php
  src/DataFixtures/UserFixtures.php
  src/DataFixtures/UserSituationFixtures.php
  src/Entity/Decision.php
  src/Entity/User.php
  src/Entity/UserSituation.php
  src/Form/DecisionType.php
  src/Form/ExpertUsersAutocompleteField.php
  src/Form/ImpactedUsersAutocompleteField.php
  src/Repository/UserSituationRepository.php
  symfony.lock
  templates/decision/_form.html.twig
  templates/login/index.html.twig
  yarn.lock
Labels: REVIEWED

#51 style background cards ok
  assets/styles/_background.scss
  assets/styles/_buttonTop.scss
  assets/styles/_decisionCards.scss
  assets/styles/app.scss
  assets/styles/variables.scss
  templates/components/_decisionCards.html.twig
  templates/components/_search_form.html.twig
Labels: REVIEWED

#53 profile
  assets/styles/profile.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  config/services.yaml
  migrations/Version20230627151523.php
  src/Controller/ProfileController.php
  src/Entity/User.php
  src/Form/UserType.php
  symfony.lock
  templates/components/_navbar.html.twig
  templates/profile/index.html.twig
  webpack.config.js
Labels: REVIEWED, Conflict resolve

#55 fix_migration
  composer.json
  composer.lock
  migrations/Version20230705080703.php
Labels: REVIEWED

#54 workflow
  composer.json
  composer.lock
  config/packages/security.yaml
  config/packages/workflow.yaml
  graph.png
  herve.session.sql
  migrations/Version20230704143612.php
  src/Controller/DecisionController.php
  src/Controller/DecisionSearchController.php
  src/Controller/HomeController.php
  src/DataFixtures/DecisionFixtures.php
  src/DataFixtures/StatusFixtures.php
  src/Entity/Decision.php
  src/Entity/Status.php
  src/Form/DecisionType.php
  src/Form/SearchDecisionType.php
  src/Repository/DecisionRepository.php
  src/Repository/StatusRepository.php
  symfony.lock
  templates/components/_decisionCards.html.twig
  templates/components/_workflowStatus.html.twig
  templates/decision/edit.html.twig
  templates/decision/index.html.twig
  templates/decision/show.html.twig
  templates/home/index.html.twig
Labels: REVIEWED, Conflict resolve

#39 btn_drop_admin
  assets/controllers.json
  assets/styles/admin_user.scss
  composer.json
  composer.lock
  config/bundles.php
  config/routes/ux_live_component.yaml
  package.json
  src/Controller/AdminController.php
  src/Entity/User.php
  src/Form/UserStatusType.php
  src/Twig/Components/RoleComponent.php
  symfony.lock
  templates/admin/admin_user/index.html.twig
  templates/components/role.html.twig
  yarn.lock
Labels: REVIEWED, Conflict resolve

#56 workflow conflict
  config/packages/workflow.yaml
  grahp.png
  src/Entity/Decision.php
  templates/components/_workflowStatus.html.twig
Labels: REVIEWED

#60 fix
  src/DataFixtures/UserFixtures.php
Labels: REVIEWED

#58 Fixfix
  assets/styles/_navbar.scss
  assets/styles/home.scss
  assets/styles/login.scss
  assets/styles/signup.scss
  assets/styles/variables.scss
  templates/components/_decisionCards.html.twig
  templates/components/_footer.html.twig
  templates/home/index.html.twig
Labels: REVIEWED, Conflict resolve

#49 reset-password
  assets/styles/reset-password.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/mailer.yaml
  config/packages/messenger.yaml
  config/packages/reset_password.yaml
  config/services.yaml
  migrations/Version20230704174131.php
  src/Controller/RegistrationController.php
  src/Controller/ResetPasswordController.php
  src/Entity/ResetPasswordRequest.php
  src/Form/ChangePasswordFormType.php
  src/Form/ResetPasswordRequestFormType.php
  src/Repository/ResetPasswordRequestRepository.php
  symfony.lock
  templates/login/index.html.twig
  templates/reset_password/check_email.html.twig
  templates/reset_password/email.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
  webpack.config.js
Labels: REVIEWED, Conflict resolve

#52 upload ok
  assets/styles/addDecision.scss
  assets/styles/admin_user.scss
  composer.json
  composer.lock
  config/packages/vich_uploader.yaml
  config/services.yaml
  migrations/Version20230703151533.php
  migrations/Version20230704135248.php
  src/Controller/AdminController.php
  src/Entity/Category.php
  src/Entity/Decision.php
  src/Form/CategoryType.php
  src/Form/DecisionType.php
  symfony.lock
  templates/admin/admin_category/_delete_form.html.twig
  templates/admin/admin_category/_form.html.twig
  templates/admin/admin_category/index.html.twig
  templates/admin/admin_user/index.html.twig
  templates/admin/admin_user/new.html.twig
  templates/base.html.twig
  templates/decision/_form.html.twig
  templates/decision/new.html.twig
Labels: REVIEWED

#62 account_btn_activate_desactivate_V2(liveComponent)
  assets/styles/admin_user.scss
  migrations/Version20230706082757.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Twig/Components/ActivationSwitchComponent.php
  templates/admin/admin_user/index.html.twig
  templates/components/activationSwitch.html.twig
Labels: REVIEWED, Conflict resolve

#66 admin_search_button
  assets/styles/admin_user.scss
  src/Controller/AdminController.php
  src/Form/UserSearchType.php
  src/Repository/UserRepository.php
  templates/admin/admin_user/_delete_form.html.twig
  templates/admin/admin_user/_form.html.twig
  templates/admin/admin_user/edit.html.twig
  templates/admin/admin_user/index.html.twig
  templates/admin/admin_user/new.html.twig
Labels: REVIEWED

#69 fix CKEditor
  config/packages/fos_ckeditor.yaml
  config/packages/twig.yaml
  webpack.config.js
Labels: REVIEWED

#70 dev to main
  config/packages/fos_ckeditor.yaml
  config/packages/twig.yaml
  webpack.config.js
Labels: REVIEWED

#71 admin connexion/deconnexion
  templates/components/_navbar.html.twig
  templates/components/_navbar_admin.html.twig
Labels: REVIEWED

#68 inscription: mail admin et mail user
  src/Controller/RegistrationController.php
  src/Entity/User.php
  src/Twig/Components/ActivationSwitchComponent.php
  templates/mail/activateUserEmail.html.twig
  templates/mail/newUserEmail.html.twig
Labels: REVIEWED

#75 Searchbar live component
  composer.json
  composer.lock
  config/routes.yaml
  templates/components/_search_form.html.twig
  templates/home/index.html.twig
Labels: REVIEWED

#63 notif email
  src/Controller/DecisionController.php
  templates/baseEmail.html.twig
  templates/decision/newEmailExpert.html.twig
  templates/decision/newEmailImpacted.html.twig
Labels: REVIEWED

#80 Fix footer
  assets/images/arrow.svg
  assets/styles/_decisionCards.scss
  assets/styles/_navbar.scss
  assets/styles/home.scss
  assets/styles/variables.scss
  templates/base.html.twig
  templates/components/_footer.html.twig
  templates/components/_navbar.html.twig
  templates/components/_search_form.html.twig
  templates/home/index.html.twig
Labels: REVIEWED

#82 decision user id ok
  src/Controller/DecisionController.php
  templates/components/_navbar.html.twig
Labels: REVIEWED, Conflict resolve

#79 S06 u53 notification
  assets/styles/_navbar.scss
  assets/styles/app.scss
  composer.json
  composer.lock
  migrations/Version20230706131203.php
  src/Controller/DecisionController.php
  src/DataFixtures/NotificationFixtures.php
  src/Entity/Decision.php
  src/Entity/Notification.php
  src/Entity/User.php
  src/Repository/NotificationRepository.php
  src/Twig/Components/NotificationComponent.php
  src/Twig/Components/RoleComponent.php
  templates/components/_navbar.html.twig
  templates/components/notification.html.twig
Labels: REVIEWED, Conflict resolve

#81 vote systeme
  migrations/Version20230710093138.php
  src/Controller/DecisionController.php
  src/DataFixtures/VoteFixtures.php
  src/Entity/Decision.php
  src/Entity/User.php
  src/Entity/Vote.php
  src/Repository/VoteRepository.php
  src/Twig/Components/DecisionVoteComponent.php
  src/Twig/Components/RoleComponent.php
  templates/components/decisionVote.html.twig
  templates/decision/show.html.twig
Labels: REVIEWED, Conflict resolve

#84 security on button
  templates/components/decisionVote.html.twig
Labels: REVIEWED

#85 uplaod ok
  .env
  assets/styles/_decisionCards.scss
  templates/components/_decisionCards.html.twig
  templates/home/index.html.twig
Labels: REVIEWED

#86 truncate ok
  assets/styles/home.scss
  assets/styles/variables.scss
  templates/components/_decisionCards.html.twig
  templates/home/index.html.twig
Labels: REVIEWED, Conflict resolve

#87 message flash
  src/Controller/AdminCategoryController.php
  src/Controller/DecisionController.php
  src/Controller/ResetPasswordController.php
  src/DataFixtures/CategoryFixtures.php
  templates/base.html.twig
Labels: REVIEWED

#89 profil card
  assets/styles/profile.scss
  src/Controller/ProfileController.php
  src/Data/citations.php
  src/Entity/User.php
  src/Form/UserType.php
  templates/components/_navbar.html.twig
  templates/components/_navbar_admin.html.twig
  templates/profile/index.html.twig
Labels: REVIEWED, Conflict resolve

#90 fix twig avatar picture
  templates/components/_decisionCards.html.twig
  templates/home/index.html.twig
Labels: REVIEWED

#91 home page and validation ok
  assets/styles/home.scss
  src/DataFixtures/UserFixtures.php
  src/Entity/Category.php
  src/Entity/Notification.php
  src/Entity/User.php
  templates/home/index.html.twig
Labels: REVIEWED

#93 link photo avatar to profile page
  assets/styles/admin_user.scss
  templates/admin/admin_user/index.html.twig
  templates/components/_decisionCards.html.twig
  templates/home/index.html.twig
Labels: REVIEWED

#94 style decision show
  assets/styles/showDecision.scss
  templates/components/decisionVote.html.twig
  templates/decision/show.html.twig
  webpack.config.js
Labels: REVIEWED

#83 ajout de condition bouton workflow
  config/packages/workflow.yaml
  graph.png
  src/Controller/DecisionController.php
  src/Data/citations.php
  src/DataFixtures/DecisionFixtures.php
  src/DataFixtures/VoteFixtures.php
  src/Entity/Decision.php
  src/Repository/CitationRepository.php
  src/Service/WorkflowAdvancement.php
  templates/components/_workflowStatus.html.twig
Labels: REVIEWED, Conflict resolve

#96 impacted and expert user ok, and a little bite style
  assets/styles/addDecision.scss
  assets/styles/profile.scss
  assets/styles/variables.scss
  src/Controller/DecisionController.php
  src/DataFixtures/CategoryFixtures.php
  templates/components/_decisionCards.html.twig
  templates/decision/_form.html.twig
  templates/decision/edit.html.twig
  templates/decision/new.html.twig
  templates/decision/show.html.twig
  templates/profile/index.html.twig
Labels: REVIEWED, Conflict resolve

#130 fix#106_profil_picture
  templates/profile/index.html.twig
Labels: REVIEWED

#133 issue ok
  templates/decision/_form.html.twig
Labels: REVIEWED

#134 fix suppression des catégories
  src/Entity/Decision.php
  templates/admin/admin_category/index.html.twig
Labels: REVIEWED

#135 fix#122_table_header
  assets/styles/admin_user.scss
Labels: REVIEWED

#137 style bouton vote
  templates/components/decisionVote.html.twig
  templates/icons/dislike.svg
  templates/icons/like.svg
Labels: REVIEWED

#138 fix_date_newDecision
  src/Entity/Decision.php
Labels: REVIEWED

#143 upload categorie ok
  config/packages/vich_uploader.yaml
  config/services.yaml
  templates/admin/admin_category/_delete_form.html.twig
  templates/login/index.html.twig
  templates/registration/register.html.twig
Labels: REVIEWED

#141 fix style form admin
  assets/styles/admin_user.scss
  assets/styles/styleAdmin.scss
  src/Form/CategoryType.php
  templates/admin/admin_category/_delete_form.html.twig
  templates/admin/admin_category/_form.html.twig
  templates/admin/admin_category/edit.html.twig
  templates/admin/admin_category/index.html.twig
  templates/admin/admin_category/new.html.twig
  templates/admin/admin_user/index.html.twig
  templates/components/role.html.twig
  webpack.config.js
Labels: REVIEWED, Conflict resolve

#145 search bar ok
  src/Form/SearchDecisionType.php
  templates/components/_search_form.html.twig
Labels: REVIEWED

#148 dev to main
  assets/styles/addDecision.scss
  assets/styles/admin_user.scss
  assets/styles/profile.scss
  assets/styles/styleAdmin.scss
  assets/styles/variables.scss
  config/packages/vich_uploader.yaml
  config/services.yaml
  src/Controller/DecisionController.php
  src/DataFixtures/CategoryFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Decision.php
  src/Form/CategoryType.php
  src/Form/SearchDecisionType.php
  templates/admin/admin_category/_delete_form.html.twig
  templates/admin/admin_category/_form.html.twig
  templates/admin/admin_category/edit.html.twig
  templates/admin/admin_category/index.html.twig
  templates/admin/admin_category/new.html.twig
  templates/admin/admin_user/index.html.twig
  templates/components/_decisionCards.html.twig
  templates/components/_search_form.html.twig
  templates/components/decisionVote.html.twig
  templates/components/role.html.twig
  templates/decision/_form.html.twig
  templates/decision/edit.html.twig
  templates/decision/new.html.twig
  templates/decision/show.html.twig
  templates/icons/dislike.svg
  templates/icons/like.svg
  templates/login/index.html.twig
  templates/profile/index.html.twig
  templates/registration/register.html.twig
  webpack.config.js
Labels: REVIEWED

#140 btn cursor ok
  assets/images/search.svg
  assets/styles/_decisionCards.scss
  templates/components/_decisionCards.html.twig
Labels: REVIEWED, Conflict resolve

#150 style height main
  assets/styles/home.scss
  assets/styles/variables.scss
  src/Entity/Decision.php
  templates/admin/admin_category/index.html.twig
  templates/admin/admin_user/index.html.twig
  templates/home/index.html.twig
Labels: REVIEWED

#147 avatar commentaire
  assets/styles/showDecision.scss
  templates/decision/show.html.twig
Labels: REVIEWED

#151 nl2br commentaire
  templates/decision/show.html.twig
Labels: REVIEWED

#153 fix entity user
  src/Entity/User.php
Labels: REVIEWED

#154 Fix admin image
  assets/styles/adminLayout.scss
  assets/styles/admin_user.scss
  templates/admin/admin_user/index.html.twig
Labels: REVIEWED

#155 fix-footer
  assets/styles/home.scss
  templates/home/index.html.twig
Labels: REVIEWED

#156 fix_register-failure
  src/Entity/User.php
Labels: REVIEWED

#149 #123 2nd
  .env
  assets/styles/showDecision.scss
  templates/decision/show.html.twig
Labels: REVIEWED, Conflict resolve

#157 fix gitignore image
  .gitignore
  public/uploads/avatar/.gitignore
  public/uploads/images/category/.gitignore
Labels: REVIEWED

#159 fix fixtures user
  src/DataFixtures/DecisionFixtures.php
  src/DataFixtures/UserFixtures.php
Labels: REVIEWED

#160 fix_myDecision_empty
  assets/styles/_decisionCards.scss
  templates/components/_decisionCards.html.twig
  templates/components/_search_form.html.twig
  templates/home/index.html.twig
  templates/status/myDecision.html.twig
Labels: REVIEWED

#162 fix_decision_show
  src/DataFixtures/DecisionFixtures.php
Labels: REVIEWED

#158 Profile navbar ok
  assets/styles/_navbar.scss
  public/uploads/images/decision/.gitignore
  src/Controller/LoginController.php
  templates/components/_navbar.html.twig
  templates/components/_navbar_admin.html.twig
  templates/decision/show.html.twig
Labels: REVIEWED, Conflict resolve

#163 Decisions show ok
  src/Controller/AdminController.php
  src/Controller/DecisionController.php
  templates/admin/admin_category/index.html.twig
  templates/admin/admin_decision/index.html.twig
  templates/components/_navbar_admin.html.twig
  templates/decision/index.html.twig
  templates/home/index.html.twig
  templates/icons/eye.svg
Labels: REVIEWED

#166 avatat ok
  templates/components/_navbar.html.twig
  templates/components/_navbar_admin.html.twig
  templates/profile/index.html.twig
Labels: REVIEWED

#165 home card
  assets/styles/_decisionCards.scss
  templates/components/_decisionCards.html.twig
  templates/home/index.html.twig
Labels: REVIEWED

#167 style notif
  assets/styles/_navbar.scss
  templates/components/notification.html.twig
Labels: REVIEWED, Conflict resolve

#152 Fix admin form
  assets/styles/adminLayout.scss
  assets/styles/admin_user.scss
  assets/styles/styleAdmin.scss
  public/uploads/images/decision/capture-d-ecran-2023-03-27-a-10-59-44-64b69ccd886cf300282501.png
  public/uploads/images/decision/tribune-stade-de-la-source-64be2dfb078ff936534346.jpg
  templates/admin/admin_category/edit.html.twig
  templates/admin/admin_category/index.html.twig
  templates/admin/admin_category/new.html.twig
Labels: REVIEWED, Conflict resolve

#169 ok
  assets/styles/profile.scss
  templates/components/_navbar_admin.html.twig
  templates/profile/index.html.twig
Labels: REVIEWED

#170 img profile ok
  assets/styles/_navbar.scss
  assets/styles/profile.scss
Labels: REVIEWED, Conflict resolve

#164 page archive
  src/Controller/DecisionController.php
  templates/components/_navbar.html.twig
  templates/decision/archive.html.twig
Labels: conflict

#171 DAYVETOWMAINE
  .env
  .gitignore
  assets/images/search.svg
  assets/styles/_decisionCards.scss
  assets/styles/_navbar.scss
  assets/styles/adminLayout.scss
  assets/styles/admin_user.scss
  assets/styles/home.scss
  assets/styles/profile.scss
  assets/styles/showDecision.scss
  assets/styles/styleAdmin.scss
  assets/styles/variables.scss
  public/uploads/avatar/.gitignore
  public/uploads/images/category/.gitignore
  public/uploads/images/decision/.gitignore
  public/uploads/images/decision/capture-d-ecran-2023-03-27-a-10-59-44-64b69ccd886cf300282501.png
  public/uploads/images/decision/gojo-64b4ef1f77cee180180134.png
  public/uploads/images/decision/tribune-stade-de-la-source-64be2dfb078ff936534346.jpg
  src/Controller/AdminController.php
  src/Controller/DecisionController.php
  src/Controller/LoginController.php
  src/DataFixtures/DecisionFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Decision.php
  src/Entity/User.php
  templates/admin/adminLayout.html.twig
  templates/admin/admin_category/edit.html.twig
  templates/admin/admin_category/index.html.twig
  templates/admin/admin_category/new.html.twig
  templates/admin/admin_decision/index.html.twig
  templates/admin/admin_user/index.html.twig
  templates/components/_decisionCards.html.twig
  templates/components/_navbar.html.twig
  templates/components/_navbar_admin.html.twig
  templates/components/_search_form.html.twig
  templates/components/notification.html.twig
  templates/decision/archive.html.twig
  templates/decision/index.html.twig
  templates/decision/show.html.twig
  templates/home/index.html.twig
  templates/icons/eye.svg
  templates/profile/index.html.twig
  templates/status/myDecision.html.twig
Labels: REVIEWED

#172 style comment and other things
  assets/images/favicon.jpg
  assets/styles/addDecision.scss
  assets/styles/adminLayout.scss
  assets/styles/showDecision.scss
  src/DataFixtures/DecisionFixtures.php
  templates/admin/admin_decision/index.html.twig
  templates/admin/index.html.twig
  templates/base.html.twig
  templates/components/decisionVote.html.twig
  templates/decision/archive.html.twig
  templates/decision/show.html.twig
  templates/home/index.html.twig
  templates/status/index.html.twig
  templates/status/myDecision.html.twig
Labels: REVIEWED

#174 com fixtures
  src/DataFixtures/CommentFixtures.php
Labels: REVIEWED

#173 new fixtures
  src/DataFixtures/DecisionFixtures.php
  src/DataFixtures/VoteFixtures.php
  src/Service/WorkflowAdvancement.php
Labels: REVIEWED

#177 last modifications
  assets/styles/showDecision.scss
  templates/components/decisionVote.html.twig
  templates/decision/show.html.twig
Labels: REVIEWED
